# **TUGAS NUMPY**

---

Nama: Orie Abyan Maulana

NIM: 245150207111050

Setelah mengikuti workshop Numpy dan Pandas, tentunya kalian sudah mulai memahami hal-hal apa saja yang akan dilakukan oleh Data Scientist dengan Numpy. Sekarang, saatnya mengukur kemampuan kalian dari apa yang telah kalian dapatkan pada workshop sebelumnya.

**Deadline: Jumat, 21 Februari 2025**


# **📊 Numpy Exercise 📊**

Selamat datang di latihan eksplorasi data menggunakan **Numpy**!  

---

## **📌 Soal 1: Regresi Linear** 📝

Saat offline/online assessment kemarin ada persoalaan **Regresi Linear**, nah coba kamu buat menggunakan python dan numpy termasuk poin-poin berikut: <br>
✅ Fungsi regresi mampu menerima array A dan array B dan memprediksi slope dan intercept<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X <br>

In [107]:
import numpy as np

In [108]:
array_A = np.array([3, 5, 7, 10, 15])
array_B = np.array([40, 36, 33, 28, 22])

def find_slope(x, y):
    return ((np.sum(y)*np.sum(x**2)) - np.sum(x) * np.sum(x*y)) / (len(x) * np.sum(x**2) - (np.sum(x))**2)

def find_intercept(x, y):
    return ((len(y) * np.sum(x*y) - np.sum(x)*np.sum(y)) / len(y)*sum(x**2) - (np.sum(x))**2) 

m = find_slope(array_A, array_B)
b = find_intercept(array_A, array_B)

def find_equation(x):
    return m*x + b

x = 10
y = find_equation(x)

print(f"Slope\t\t: {m} \nIntercept\t: {b} \nPredict Value\t: {y}")



Slope		: 43.70909090909091 
Intercept	: -55048.0 
Predict Value	: -54610.90909090909


## **📌 Soal 2: Regresi Polinomial** 📝

Saat offline/online assessment kemarin ada persoalan **Regresi Linear**, nah sekarang coba kamu buat **Regresi Polinomial** menggunakan Python dan NumPy, termasuk poin-poin berikut:<br>
✅ Fungsi regresi mampu menerima array A dan array B serta menyesuaikan data dengan polinomial derajat tertentu.<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X.<br>
✅ Hasil regresi mencetak koefisien polinomial yang dihasilkan.<br>

## **📌 Soal 3: Random Values Array** 📝

Pertama-tama, buatlah **Array Integer 10x10x10** dengan elemen **random** dan carikan:<br>
1️⃣ Cari elemen minimum dan maksimum dalam array tersebut?<br>
2️⃣ Carilah rata-rata dan median seluruh elemen dalam array tersebut?<br>

In [109]:
array_random = np.random.rand(10, 10, 10)

min_value = np.amin(array_random) 
max_value = np.amax(array_random) 


print(f'min value: {min_value}')
print(f'max value: {max_value}')


min value: 0.00011153688968057462
max value: 0.9993671876739108


In [110]:
mean_value = np.mean(array_random)
median_value = np.median(array_random)

print(f"mean value: {mean_value}")
print(f'median value: {median_value}')

mean value: 0.4892440905967637
median value: 0.4905202197780321


## **📌 Soal 4: 2D Array Shenanigans** 📝

Tugas kamu disini adalah membuat **Array 2D** sesuai ketentuan masing-masing soal: <br>
1️⃣ Buatlah **array 10x10** yang memiliki angka "5" sebagai bingkai di seluruh tepi luar dan bagian dalam (selain array) berisi "8"? <br>
2️⃣ Buatlah **array 2d 8x8** dengan pola seperti **checkboard/catur** (1 untuk kotak hitam, 0 untuk kotak putih)?<br>
3️⃣ Buatlah **array 2d 15x15** dengan aturan sebagai berikut:
- Jika suatu angka dapat dibagi 2, isi dengan 2.
- Jika suatu angka dapat dibagi 3, isi dengan 3.
- Jika suatu angka dapat dibagi 5, isi dengan 5.
- Jika suatu angka dapat dibagi oleh lebih dari satu kondisi (misal, 6 bisa dibagi 2 & 3), maka simpan gabungan angka tersebut (misal, 6 → "23", 15 → "35").
- Jika tidak memenuhi kondisi apa pun, isi dengan 0.

In [111]:
array_4_1 = np.full((10,10), 8)

array_4_1[:, 0] = 5
array_4_1[0, :] = 5
array_4_1[:, -1] = 5
array_4_1[-1, :] = 5

print(array_4_1)

[[5 5 5 5 5 5 5 5 5 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 5 5 5 5 5 5 5 5 5]]


In [112]:
array_4_2 = np.ones((8, 8))
array_4_2[::2, 1::2] = 0
array_4_2[1::2, ::2] = 0
array_4_2

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [113]:
array_4_3 = np.random.randint(1, 10000, size=(15,15))

for i in range(15):
    for j in range(15):
        result = ''
        if array_4_3[i, j] % 2 == 0:
            result += '2'
        if array_4_3[i, j] % 3 == 0:
            result += '3'
        if array_4_3[i, j] % 5 == 0:
            result += '5'
        array_4_3[i, j] = result if result else '0' 

print(array_4_3)

[[  0 235   0  23   0   5   2   3   3   2   3   2  25   0   0]
 [ 25   5   2   0   3  23   5  23   0   2   2  35   0   3   0]
 [  3  35   2  25   2 235  23   0   2  23   2 235  25  23   0]
 [  3   2   5   0  23  23  23  23  23   0   0   3   2   2   3]
 [  2   0   5   2  23  25   2   0  23   2   0   2  23   0   0]
 [  0   3   2   2   2   0   2   3  23   0   3  23   0   0   3]
 [ 23   0  23  23   0   2   0  23   3   3   3   0   2   0  35]
 [  2   3   2   3   2   0   2   2   0   2  23  23   5   0   2]
 [  0  23   3   2   3   3  23   2   2   5   2   0   0   0   0]
 [  2   2  23   0  23   2   0  35   5  23   0  23   2   5   2]
 [ 25   2   0   0   0   2  35  23   3   2   2   2   2   0   0]
 [  2   2  23   2   2  23   0   2  23   0   3  23  23  23   5]
 [  3   0  23   0   3  23   3   0   2   2   0   0   0  25   2]
 [  2   2  25   3  25  35   2   2   0   5   2   3   0   0   2]
 [  0   0  25   2   2   2 235   0  23   2   0   2   2   0   0]]


## **📌 Soal 5: Time & Date** 📝

Kamu disini diminta untuk memanfaatkan fitur numpy untuk tanggal: <br>
1️⃣ Bagaimana dengan numpy, kamu bisa mendapatkan tanggal hari ini, kemarin dan esok hari?<br>
2️⃣ Tampilkan hari yang ada di bulan Mei tahun 2020?<br>

In [114]:
hari_ini = np.datetime64('today', 'D')
besok = hari_ini + np.timedelta64(1, 'D')
kemarin = hari_ini - np.timedelta64(1, 'D')

print(f"Hari ini tanggal\t: {hari_ini}")
print(f"Besok tanggal\t\t: {besok}")
print(f"Kemarin tanggal\t\t: {kemarin}")



Hari ini tanggal	: 2025-02-21
Besok tanggal		: 2025-02-22
Kemarin tanggal		: 2025-02-20


## **📌 Soal 6: Slicing** 📝

Jika diketahui array `A`, maka buatlah program untuk mendapatkan elemen dibawah ini:
```python
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])
```

1️⃣ Ambil elemen yang berada pada baris `ke-4` dan kolom `ke-2` dari array `A` <br>
2️⃣ Buat `array 2D` yang hanya berisi bilangan prima dari `A` <br>
3️⃣ Ambil elemen-elemen yang berada di tepi luar dari array `A` dan gabungkan menjadi `Satu array 1D`. <br>
4️⃣ Dapatkan subbarray berikut:
```python
[[20, 40, 60],
 [80, 100, 120],
 [140, 160, 180],
 [200, 220, 240],
 [260, 280, 300]]
```
5️⃣ Dapatkan subbarray berikut:
```python
 [[30, 40],
 [90, 100],
 [150, 160],
 [210, 220]]
```

In [115]:
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])

In [116]:
array_6_1 = A[3, 1] 
array_6_1

200

In [117]:
def is_prime(number):
    if number <= 1:
        return False
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            return False
    return True

prime = A[np.vectorize(is_prime)(A)]
prime

array([], dtype=int32)

In [118]:
array_6_3_1 = A[:,0]
array_6_3_2 = A[:,-1]
array_6_3_3 = A[0,:]
array_6_3_4 = A[-1,:]
array_6_3 = np.concatenate((array_6_3_1, array_6_3_2, array_6_3_3, array_6_3_4), axis=None)
array_6_3


array([ 10,  70, 130, 190, 250,  60, 120, 180, 240, 300,  10,  20,  30,
        40,  50,  60, 250, 260, 270, 280, 290, 300])

In [119]:
array_6_4 = A[::, 1::2]
array_6_4

array([[ 20,  40,  60],
       [ 80, 100, 120],
       [140, 160, 180],
       [200, 220, 240],
       [260, 280, 300]])

In [120]:
array_6_5 = A[0:4, 2:4]
array_6_5

array([[ 30,  40],
       [ 90, 100],
       [150, 160],
       [210, 220]])

## **📌 Soal 7: Ekspansi Array** 📝

Jika kamu memiliki array ***Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]***, buatlah kode untuk membuat array R berupa: <br>
***R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]***?

In [121]:
Z = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
R = np.array([Z[i:i+4] for i in range(len(Z)-3)])
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])